package com.listify.backend.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Map;

/**
 * Represents a chat message for transport between the client and server.
 * <p>
 * This Data Transfer Object (DTO) is used to send and receive chat message data,
 * particularly over WebSocket connections. It contains all the necessary information
 * for the client to render the message correctly in the UI.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class ChatMessageDTO {

    /**
     * The main textual content of the message.
     */
    private String content;

    /**
     * The unique identifier of the user who sent the message.
     */
    private Long senderId;

    /**
     * The unique identifier of the group chat to which this message belongs.
     */
    private Long groupId;

    /**
     * The display name of the user who sent the message.
     * This is included to avoid an extra client-side lookup for the sender's details.
     */
    private String senderName;

    /**
     * The timestamp of when the message was sent, represented as an ISO-8601 string.
     */
    private String timestamp;

    /**
     * The type of the message (e.g., "TEXT", "POLL", "JOIN_EVENT").
     * This allows the client to render the message differently based on its purpose.
     */
    private String type;

    /**
     * A map for storing additional, unstructured data related to the message.
     * This is particularly useful for special message types, such as polls,
     * where it might contain poll options and vote counts.
     */
    private Map<String, Object> metadata;

    /**
     * The unique identifier of the message, typically generated by the database.
     */
    private Long id;
}