package com.listify.backend.dto;

import java.util.List;

/**
 * Represents the response payload for a financial payment sent to the client.
 * <p>
 * This Data Transfer Object (DTO) provides a comprehensive view of a payment,
 * intended for display in the user interface. Unlike the request DTO, it replaces
 * simple user IDs with nested {@link UserDTO} objects containing more details
 * like usernames and avatar URLs.
 */
public class PaymentResponseDTO {

    /**
     * The unique identifier of the payment, generated by the database.
     */
    public Long id;

    /**
     * The descriptive title of the payment (e.g., "Weekly Groceries").
     */
    public String title;

    /**
     * The total amount of the payment.
     */
    public Double amount;

    /**
     * The date the payment was made, formatted as a string (e.g., "YYYY-MM-DD").
     */
    public String date;

    /**
     * An optional URL pointing to an image of a receipt or invoice for this payment.
     */
    public String imageUrl;

    /**
     * A simplified representation of the user who made the payment.
     * Contains details like ID, username, and avatar URL.
     */
    public UserDTO paidBy;

    /**
     * A list of simplified user representations indicating who this payment was shared with.
     */
    public List<UserDTO> sharedWith;

    /**
     * A nested static class providing a simplified, public-facing representation of a user.
     * <p>
     * This is used to avoid exposing the entire internal {@link com.listify.backend.model.User}
     * entity in API responses.
     */
    public static class UserDTO {
        /**
         * The unique identifier of the user.
         */
        public Long id;

        /**
         * The display name of the user.
         */
        public String username;

        /**
         * The URL pointing to the user's avatar image.
         */
        public String avatarUrl;
    }
}