package com.listify.backend.model;

import jakarta.persistence.*;

/**
 * Represents the link between a {@link Payment} and a {@link User} with whom that payment is shared.
 * This class acts as a join entity, effectively modeling a many-to-many relationship
 * between payments and the users involved in the split. Each entry in this table
 * signifies: "User X is involved in sharing the cost of Payment Y".
 * Each entry must be linked to a non-null payment and a non-null user.
 *
 * @author Listify Team
 * @version 1.0
 * @see Payment
 * @see User
 */
@Entity
public class PaymentSharedWith {

    /**
     * The unique identifier for this join entry.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The payment to which this entry refers.
     * This field cannot be null.
     */
    @ManyToOne
    @JoinColumn(name = "payment_id", nullable = false)
    private Payment payment;

    /**
     * The user with whom the payment is shared.
     * This field cannot be null.
     */
    @ManyToOne
    @JoinColumn(name = "shared_with_id", nullable = false)
    private User sharedWith;

    // Getter & Setter
    /**
     * Gets the ID of the entry.
     * @return the ID.
     */
    public Long getId() { return id; }

    /**
     * Sets the ID of the entry.
     * @param id the new ID.
     */
    public void setId(Long id) { this.id = id; }

    /**
     * Gets the associated payment.
     * @return the {@link Payment} instance.
     */
    public Payment getPayment() { return payment; }

    /**
     * Sets the associated payment.
     * @param payment the new {@link Payment} instance.
     */
    public void setPayment(Payment payment) { this.payment = payment; }

    /**
     * Gets the user with whom the payment is shared.
     * @return the {@link User} instance.
     */
    public User getSharedWith() { return sharedWith; }

    /**
     * Sets the user with whom the payment is shared.
     * @param sharedWith the new {@link User} instance.
     */
    public void setSharedWith(User sharedWith) { this.sharedWith = sharedWith; }
}

