package com.listify.backend.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Represents a product suggestion submitted by a user or a visitor.
 * This entity is used to collect suggestions for new products that could be added
 * to a master product catalog. Unlike most other entities, this class uses a {@link UUID}
 * as its primary key. This ID is typically generated by the application
 * (e.g., the client or a backend service) before persistence, not by the database.
 * Lombok is used to reduce boilerplate code for getters, setters, and constructors.
 *
 * @author Listify Team
 * @version 1.0
 */
@Entity
@Table(name = "product_suggestions")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class ProductSuggestion {

    /**
     * The unique identifier for the product suggestion.
     * It uses a {@link UUID} as the primary key. This value must be explicitly set
     * by the application before the entity is persisted, as no generation
     * strategy is defined.
     */
    @Id
    @Column(name = "id")
    private UUID id;

    /**
     * The name of the suggested product (e.g., "Oat Milk Barista").
     */
    private String name;

    /**
     * The suggested category for the product.
     */
    private String category;

    /**
     * The timestamp indicating when the suggestion was created.
     */
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    /**
     * The email address of the person who submitted the suggestion.
     * This allows submissions from non-registered users as well.
     */
    @Column(name = "creator_email")
    private String creatorEmail;

}

